### ISSUE TITLE
[Solved]The objects in TUISimulator's UI systeam has disappeared

### ISSUE THREAD

**Issue by Kakei08** [gregharding/TUIOSimulator#5]
Hi,when I was using Touchdesigner today, I noticed that the Objects (colorful digital squares) on the TUIOSimulator operation page suddenly disappeared, which were displayed normally until today.Hope can received your comment,thank you!
The UI is showing like this ↓ I screen shot that
![screen shot](https://github.com/gregharding/TUIOSimulator/assets/59464997/380392bd-181d-4fb4-bcc5-28c23b8a455a)

**Comment by gregharding** [comment]
hey @Kakei08, sorry you had some issues - I hope everything's working ok again!

**Comment by Kakei08** [comment]
> hey @Kakei08, sorry you had some issues - I hope everything's working ok again!

Thanks for your reply, I found the solution very simple, just zoom in/out the application box and you can see the objects:)And thanks again,great software!

**Comment by gregharding** [comment]
Hmm, sounds like it could be a depth buffer issue or something.

And no worries! My app is pretty simple really, the hard work was done by Valentin Simonov, the author of TouchScript. My TUIOSimulator and the [TUIOListener](https://github.com/gregharding/TUIOListener) commandline tools were useful for us when we were building interactive touch tables for museum installations so I thought I'd share them.

It would be nice to keep them updated with the latest Unity but support for TouchScript ended years ago so it's a bit out of date now, unfortunately.

**Comment by Kakei08** [comment]
> 嗯，听起来可能是深度缓冲问题或其他问题。
> 
> 不用担心！我的应用程序真的很简单，艰苦的工作是由 TouchScript 的作者 Valentin Simonov 完成的。我的 TUIOSimulator 和[TUIOListener](https://github.com/gregharding/TUIOListener)命令行工具在我们为博物馆设施构建交互式触摸桌时对我们很有用，所以我想我应该分享它们。
> 
> 很高兴让他们使用最新的 Unity 进行更新，但对 TouchScript 的支持在几年前就结束了，所以现在有点过时了，不幸的是。

![record](https://github.com/gregharding/TUIOSimulator/assets/59464997/024df557-43a6-4d6e-a3e5-a9f0f660f02b)
My English is not very good, so I recorded a gif to demonstrate how to solve the problem. I found someone in the problem who encountered the same situation as me, and the solution is actually very simple.
Thank you again for your work and providing a very convenient presentation for my graduation design, and I am looking forward to being exposed to your other works in the future.

**Comment by gregharding** [comment]
Oh ok, no problem - it's just the aspect ratio of the screen changing which is hiding content. In Unity you can choose to respect the vertical or horizontal aspect ratio of the camera view when resizing the application window. I didn't need to make the app work in any aspect ratio at the time because just scaling to and from the square content area was fine.

I'm glad you're finding this old tool useful! Here are some examples of our earlier interactive work;
[Collect And Connect Multi-User Interactive Table](https://vimeo.com/133029484)
[WWI Aerial Reconnaissance Multi-User Interactive Table](https://vimeo.com/261424440)
