### ISSUE TITLE
Connection trouble for macos sequoia 15.0

### ISSUE THREAD

**Issue by tibettokitsune** [gregharding/TUIOSimulator#6]
Hi
After update my system to latest version (macos sequoia 15.0 for a moment) i have problem with connection. So no data recieved in my client, any logs and error "error sending TUIO" in simulator screen. Nothing changed in my software (i'm using it as c# object in unity, but before update it works fine). Have you any idea why it's can happend?

**Comment by gregharding** [comment]
I expect the issue is the updated macOS Gatekeeper which will be preventing the app from opening network connections. You will probably need to add some entitlements allowing client/server network access and codesign the app using your Apple Developer Id certificate to get things working again. If you're developing your app on the mac already this should be ok because you should have everything you need (Xcode, codesign tools, Apple Developer Account, etc).

**Comment by tibettokitsune** [comment]
Well apple just change my local ip, so need to update startup data in simulator to resolve it. Looks like not issue now :)
